extends RefCounted
## generate_element_matrix.gd — the one-way Pandora → runtime generator for the
## element interaction table (#136).
##
## Static-only helper. It is not an autoload; tools/generate_gloot.gd preloads
## it and folds its artifacts into the single drift check, so CI covers this
## table the same way it covers GLoot prototypes and the fizzle table.
##
## Emits (committed, never hand-edited):
##   res://data/generated/element_matrix.json      — both axes plus the 100
##       ordered (attack_element, defend_element) target-axis pairs
##   res://data/generated/element_matrix_rows.gd   — ElementMatrixRows, the
##       runtime constant tables read by globals/elements/element_matrix.gd
##
## THE AUTHORED DATA IS THE MULTIPLIERS; THE TOPOLOGY IS DERIVED.
## The 100 pairs are expanded from `ElementWheel.ORDER` + `ElementWheel.distance`.
## Nothing here retypes the wheel and nothing hand-enumerates a pair, so adding
## or reordering an element regenerates a correct table for free.
##
## TWO AXES, TWO TABLES. `target` rows price damage / fizzle / Soul against the
## TARGET's attunement (resolve time). `caster` rows price the CHORD bonus
## against the CASTER's attunement (compose time). They are emitted into
## separate structures and the pair matrix is built from the target rows only —
## the caster axis has no 100-row matrix at all, by design. See #133 and
## docs/prd-amendment-tactical-layer.md §9.2.

const OUT_DIR := "res://data/generated"
const MATRIX_JSON_PATH := OUT_DIR + "/element_matrix.json"
const MATRIX_ROWS_PATH := OUT_DIR + "/element_matrix_rows.gd"
const ROOT_NAME := "Element Relations"
const TARGET_AXIS := "target"
const CASTER_AXIS := "caster"
const AXES := [TARGET_AXIS, CASTER_AXIS]
const MAX_DISTANCE := 5
const GENERATED_HEADER := "GENERATED by tools/generate_element_matrix.gd from data.pandora — DO NOT EDIT."
const GENERATED_INSTRUCTION := "Change the Pandora entity and regenerate."


## Returns {json, gd, pair_count} — pure, writes nothing.
static func artifacts() -> Dictionary:
	var wheel := _wheel_ids()
	var rows_by_axis := _relation_rows_by_axis()
	var target_rows: Array = rows_by_axis[TARGET_AXIS]
	var caster_rows: Array = rows_by_axis[CASTER_AXIS]
	var pairs := _target_pairs(wheel, target_rows)

	var data := {
		"vault_id": _vault_id(),
		"provisional": true,
		"wheel_order": wheel,
		"axes": {
			"target": {
				"description":
				"Resolve time. Wheel distance from the working's element to the target's attunement. Prices damage, adds fizzle percentage points outside the magnitude multiply, and charges Soul on failure.",
				"relations": target_rows,
			},
			"caster": {
				"description":
				"Compose time. Wheel distance from the working's element to the caster's attunement. Prices the CHORD bonus only. Never consulted for damage against a target.",
				"relations": caster_rows,
			},
		},
		"pairs": pairs,
	}
	return {
		"json": JSON.stringify(data, "  ", false) + "\n",
		"gd": _rows_source(wheel, target_rows, caster_rows, pairs),
		"pair_count": pairs.size(),
	}


static func _wheel_ids() -> Array[String]:
	var elements_root := _root_by_name("Elements")
	var known := {}
	for entity: PandoraEntity in Pandora.get_all_entities(elements_root):
		if entity is PandoraCategory:
			continue
		known[entity.get_string("Element Id")] = true

	var wheel: Array[String] = []
	for element_id: StringName in ElementWheel.ORDER:
		var id := String(element_id)
		assert(known.has(id), "ElementWheel.ORDER names an element Pandora does not have: %s" % id)
		wheel.append(id)
	assert(
		wheel.size() == known.size(),
		"Pandora has elements outside ElementWheel.ORDER — the wheel is the single topology source"
	)
	return wheel


static func _relation_rows_by_axis() -> Dictionary:
	var root := _root_by_name(ROOT_NAME)
	var by_axis := {TARGET_AXIS: {}, CASTER_AXIS: {}}
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		var axis := entity.get_string("Axis")
		assert(axis in AXES, "Element relation has unknown axis '%s'" % axis)
		var distance := entity.get_integer("Distance")
		assert(
			distance >= 0 and distance <= MAX_DISTANCE,
			"Element relation distance %d is off the wheel" % distance
		)
		var bucket: Dictionary = by_axis[axis]
		assert(
			not bucket.has(distance),
			"Duplicate %s relation for distance %d — every distance resolves exactly once" % [axis, distance]
		)
		var multiplier := entity.get_float("Damage Multiplier")
		assert(multiplier > 0.0, "Element relation multiplier must be positive")
		bucket[distance] = {
			"distance": distance,
			"relation": entity.get_string("Relation Id"),
			"display_name": entity.get_string("Display Name"),
			"damage_multiplier": multiplier,
			"fizzle_add": entity.get_float("Fizzle Add"),
			"soul_on_failure": entity.get_integer("Soul On Failure"),
			"provisional": entity.get_bool("Provisional"),
		}

	var result := {}
	for axis: String in AXES:
		var bucket: Dictionary = by_axis[axis]
		var rows: Array[Dictionary] = []
		for distance in range(MAX_DISTANCE + 1):
			assert(
				bucket.has(distance),
				"The %s relation table has no row for distance %d — it must be total over 0..5" % [axis, distance]
			)
			rows.append(bucket[distance])
		result[axis] = rows

	# The caster axis prices adjacency and nothing else. Guarding it here keeps
	# a stray target-shaped edit (a Soul charge, a fizzle penalty) from quietly
	# entering the compose-time axis and taxing wheel distance twice.
	for row: Dictionary in result[CASTER_AXIS]:
		assert(
			float(row["fizzle_add"]) == 0.0 and int(row["soul_on_failure"]) == 0,
			"The caster axis must not price fizzle or Soul — that is the target axis"
		)
	return result


static func _target_pairs(wheel: Array[String], target_rows: Array) -> Array[Dictionary]:
	var by_distance := {}
	for row: Dictionary in target_rows:
		by_distance[int(row["distance"])] = row

	var pairs: Array[Dictionary] = []
	var seen := {}
	for attack_element: String in wheel:
		for defend_element: String in wheel:
			var distance := ElementWheel.distance(attack_element, defend_element)
			assert(distance >= 0, "ElementWheel could not place %s/%s" % [attack_element, defend_element])
			var key := "%s|%s" % [attack_element, defend_element]
			assert(not seen.has(key), "Duplicate ordered pair %s" % key)
			seen[key] = true
			var row: Dictionary = by_distance[distance]
			pairs.append({
				"attack_element": attack_element,
				"defend_element": defend_element,
				"distance": distance,
				"relation": row["relation"],
				"damage_multiplier": row["damage_multiplier"],
				"fizzle_add": row["fizzle_add"],
				"soul_on_failure": row["soul_on_failure"],
			})
	assert(
		pairs.size() == wheel.size() * wheel.size(),
		"Every ordered pair must resolve exactly once"
	)
	return pairs


static func _vault_id() -> String:
	var root := _root_by_name(ROOT_NAME)
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if not entity is PandoraCategory:
			return entity.get_string("Vault Id")
	return ""


static func _rows_source(
	wheel: Array[String],
	target_rows: Array,
	caster_rows: Array,
	pairs: Array[Dictionary]
) -> String:
	var source := "# %s\n# %s\n" % [GENERATED_HEADER, GENERATED_INSTRUCTION]
	source += "class_name ElementMatrixRows\nextends RefCounted\n\n"
	source += "## Two axes, two tables. TARGET_RELATION_ROWS and PAIR_ROWS are the\n"
	source += "## resolve-time lookup; CASTER_RELATION_ROWS is the compose-time lookup.\n"
	source += "## They are never merged and never share a `distance` variable.\n"
	source += "## Multipliers are PROVISIONAL (GitHub #133); the shape is canon.\n\n"
	source += "const PROVISIONAL := true\n\n"
	source += "const WHEEL_ORDER: Array[StringName] = [%s]\n\n" % _gd_name_list(wheel)
	source += "const TARGET_RELATION_ROWS: Array[Dictionary] = [\n"
	for row: Dictionary in target_rows:
		source += "\t%s,\n" % _gd_relation_row(row)
	source += "]\n\nconst CASTER_RELATION_ROWS: Array[Dictionary] = [\n"
	for row: Dictionary in caster_rows:
		source += "\t%s,\n" % _gd_relation_row(row)
	source += "]\n\nconst PAIR_ROWS: Array[Dictionary] = [\n"
	for row: Dictionary in pairs:
		source += "\t%s,\n" % _gd_pair_row(row)
	source += "]\n"
	return source


static func _gd_relation_row(row: Dictionary) -> String:
	return (
		'{"distance": %d, "relation": %s, "display_name": %s, "damage_multiplier": %s, "fizzle_add": %s, "soul_on_failure": %d}'
		% [
			int(row["distance"]),
			_gd_name(str(row["relation"])),
			_gd_string(str(row["display_name"])),
			_gd_number(float(row["damage_multiplier"])),
			_gd_number(float(row["fizzle_add"])),
			int(row["soul_on_failure"]),
		]
	)


static func _gd_pair_row(row: Dictionary) -> String:
	return (
		'{"attack_element": %s, "defend_element": %s, "distance": %d, "relation": %s, "damage_multiplier": %s, "fizzle_add": %s, "soul_on_failure": %d}'
		% [
			_gd_name(str(row["attack_element"])),
			_gd_name(str(row["defend_element"])),
			int(row["distance"]),
			_gd_name(str(row["relation"])),
			_gd_number(float(row["damage_multiplier"])),
			_gd_number(float(row["fizzle_add"])),
			int(row["soul_on_failure"]),
		]
	)


static func _gd_name_list(values: Array[String]) -> String:
	var entries: Array[String] = []
	for value: String in values:
		entries.append(_gd_name(value))
	return ", ".join(entries)


static func _gd_name(value: String) -> String:
	return "&" + _gd_string(value)


static func _gd_string(value: String) -> String:
	return JSON.stringify(value)


static func _gd_number(value: float) -> String:
	return str(value)


static func _root_by_name(root_name: String) -> PandoraCategory:
	for root in Pandora.get_all_roots():
		if root.get_entity_name() == root_name:
			return root
	assert(false, "Pandora has no %s root — run tools/seed_element_matrix.gd first" % root_name)
	return null
