extends Node
## generate_gloot.gd — the Pandora one-way data generator. The original GLoot
## bridge remains here; combatant/encounter catalogs and stable IDs use the
## same canonical-data and drift-check contract.
##
## Pandora OWNS item data. This emits the generated artifacts (committed, never
## hand-edited):
##   res://data/generated/gloot_prototree.json  — GLoot protoset (keys: size /
##       max_stack_size / weight — GLoot's own constraint keys — plus name,
##       description, equip_slot, rarity, flavour)
##   res://data/generated/item_ids.gd           — ItemIds constants; no literal
##       item path strings in code, ever
##   res://data/generated/items.pot             — gettext template for generated
##       item keys. English source text is retained as an extracted comment;
##       runtime falls back to Pandora when a key is untranslated.
##   res://locale/es.po                         — starter locale, merged on each
##       regeneration so translated rows survive data changes.
##   res://data/generated/encounters.json        — expanded encounter groups
##   res://data/generated/encounter_ids.gd       — stable EncounterIds constants
##   res://data/generated/elements.json          — elements, Triads, and casting tables
##   res://data/generated/fizzle_table.json      — fizzle formula inputs
##   res://globals/elements/elements_data.gd     — generated #89 runtime table
##   res://globals/default_fizzle_table.tres     — generated #88 runtime resource
##   res://data/generated/dom_npc_roster.json    — Dom's 60 authored townsfolk
##   res://data/generated/dom_npc_placements.json — scene anchors and offsets
##   res://dialogue/dom_townsfolk.dialogue       — thin generated placeholder dialogue
##
## Run ways:
##   - Editor: Project > Tools > Regenerate Pandora artifacts (addons/soul_meter_tools)
##   - Headless: register as temp autoload and run once (see DEPENDENCIES.md)
##   - Drift check (CI/pre-commit): run with env SOUL_METER_DRIFT_CHECK=1 —
##     exits non-zero if committed artifacts differ from a fresh generation.

const OUT_DIR := "res://data/generated"
const PROTOTREE_PATH := OUT_DIR + "/gloot_prototree.json"
const ITEM_IDS_PATH := OUT_DIR + "/item_ids.gd"
const FACTION_IDS_PATH := OUT_DIR + "/faction_ids.gd"
const NPC_IDS_PATH := OUT_DIR + "/npc_ids.gd"
const DOM_NPC_ROSTER_PATH := OUT_DIR + "/dom_npc_roster.json"
const DOM_NPC_PLACEMENTS_PATH := OUT_DIR + "/dom_npc_placements.json"
const DOM_NPC_DIALOGUE_PATH := "res://dialogue/dom_townsfolk.dialogue"
const ENCOUNTERS_PATH := OUT_DIR + "/encounters.json"
const ENCOUNTER_IDS_PATH := OUT_DIR + "/encounter_ids.gd"
const ELEMENTS_JSON_PATH := OUT_DIR + "/elements.json"
const FIZZLE_JSON_PATH := OUT_DIR + "/fizzle_table.json"
const COMBAT_IDENTITY_PATH := OUT_DIR + "/combat_identity.json"
const ELEMENTS_DATA_PATH := "res://globals/elements/elements_data.gd"
const FIZZLE_TABLE_PATH := "res://globals/default_fizzle_table.tres"
const POT_PATH := OUT_DIR + "/items.pot"
const LOCALE_PO_PATH := "res://locale/es.po"
const LOCALE_CODE := "es"
const GENERATED_HEADER := "GENERATED by tools/generate_gloot.gd from data.pandora — DO NOT EDIT."
const GENERATED_INSTRUCTION := "Change the Pandora entity and regenerate."
const ELEMENT_ORDER := ["suul", "bloei", "aqua", "khor", "terra", "daar", "molm", "scor", "nul", "strom"]
const TRIAD_ORDER := ["dayspring", "fruiting", "rivermouth", "founding", "vault", "barrow", "pyre", "cinderfall", "stillpoint", "thunderhead"]
const PORTRAIT_VARIANT_COUNT := 10
const SAFE_PORTRAIT_EXTENSIONS := ["png", "jpg", "jpeg", "svg", "webp", "tga"]
const QUEST_INVOLVEMENT_TYPES := [
	"giver", "target", "information", "gate", "state_change", "reputation_reaction"
]
const StableIdsScript := preload("res://globals/stable_ids.gd")


func _ready() -> void:
	await get_tree().process_frame
	if not Pandora.is_loaded():
		Pandora.load_data()
	var check_only: bool = OS.get_environment("SOUL_METER_DRIFT_CHECK") == "1"
	var result := generate(check_only)
	if check_only:
		if result["drift"]:
			printerr(
				"GLOOT-GEN: DRIFT — committed artifacts differ from Pandora. Regenerate and commit."
			)
			get_tree().quit(1)
			return
		print("GLOOT-GEN: no drift.")
	else:
		print(
			(
				"DATA-GEN: wrote %d item prototypes, %d encounters, and %d Dom NPCs."
				% [result["count"], result["encounter_count"], result["npc_count"]]
			)
		)
	get_tree().quit()


## Walks the Pandora roots and builds every derived runtime artifact.
## Returns {count, encounter_count, drift} — when check_only, nothing is written.
static func generate(check_only: bool = false) -> Dictionary:
	var items_root: PandoraCategory = null
	for root in Pandora.get_all_roots():
		if root.get_entity_name() == "Items":
			items_root = root
			break
	assert(items_root != null, "Pandora has no Items root — run tools/seed_pandora.gd first")

	# Collect entities with their category-chain path below Items.
	var protos := {}  # path -> properties dict
	for ent: PandoraEntity in Pandora.get_all_entities(items_root):
		if ent is PandoraCategory:
			continue
		var chain := PackedStringArray()
		var cat: PandoraCategory = Pandora.get_category(ent.get_category_id())
		while cat != null and cat.get_entity_id() != items_root.get_entity_id():
			chain.insert(0, _slug(cat.get_entity_name()))
			cat = Pandora.get_category(cat.get_category_id()) if cat.get_category_id() else null
		chain.append(_slug(ent.get_entity_name()))
		var path := "/".join(chain)

		var props := {
			"name": ent.get_string("Display Name"),
			"description": ent.get_string("Description"),
			"size": var_to_str(ent.get_vector2i("Grid Size")),
			"max_stack_size": ent.get_integer("Max Stack Size"),
			"weight": ent.get_float("Weight"),
			"rarity": ent.get_string("Rarity"),
			"flavour": ent.get_string("Flavour"),
		}
		var slot := ent.get_string("Equip Slot")
		if not slot.is_empty():
			props["equip_slot"] = slot
		protos[path] = props

	var paths := protos.keys()
	paths.sort()  # deterministic output — required for the drift check

	# --- artifact 1: the GLoot protoset JSON ---
	var ordered := {}
	for p in paths:
		ordered[p] = protos[p]
	var json_text := JSON.stringify(ordered, "  ", false) + "\n"

	# --- artifact 2: ItemIds constants ---
	var ids_text := "# %s\n# %s\nclass_name ItemIds\n\n" % [GENERATED_HEADER, GENERATED_INSTRUCTION]
	for p: String in paths:
		ids_text += 'const %s := "%s"\n' % [p.to_upper().replace("/", "_").replace("-", "_"), p]
	var faction_ids_text := _vault_ids_source("Factions", "FactionIds")
	var npc_ids_text := _npc_ids_source()
	var npc_artifacts := _npc_artifacts()
	var npc_roster_text: String = npc_artifacts["roster_json"]
	var npc_placements_text: String = npc_artifacts["placements_json"]
	var npc_dialogue_text: String = npc_artifacts["dialogue"]
	var encounter_artifacts := _encounter_artifacts()
	var encounters_text: String = encounter_artifacts["json"]
	var encounter_ids_text: String = encounter_artifacts["ids"]
	var element_artifacts := _element_artifacts()
	var elements_text: String = element_artifacts["json"]
	var elements_data_text: String = element_artifacts["gd"]
	var fizzle_artifacts := _fizzle_artifacts()
	var fizzle_text: String = fizzle_artifacts["json"]
	var fizzle_resource_text: String = fizzle_artifacts["tres"]
	var combat_identity_text := _combat_identity_artifact()

	# --- artifact 3: gettext template of generated item keys ---
	var item_entries := _item_entries(protos, paths)
	var pot := _build_pot(item_entries)
	var locale_po := _merge_locale_po(LOCALE_PO_PATH, item_entries)

	var drift := (
		_differs(PROTOTREE_PATH, json_text)
		or _differs(ITEM_IDS_PATH, ids_text)
		or _differs(FACTION_IDS_PATH, faction_ids_text)
		or _differs(NPC_IDS_PATH, npc_ids_text)
		or _differs(DOM_NPC_ROSTER_PATH, npc_roster_text)
		or _differs(DOM_NPC_PLACEMENTS_PATH, npc_placements_text)
		or _differs(DOM_NPC_DIALOGUE_PATH, npc_dialogue_text)
		or _differs(ENCOUNTERS_PATH, encounters_text)
		or _differs(ENCOUNTER_IDS_PATH, encounter_ids_text)
		or _differs(ELEMENTS_JSON_PATH, elements_text)
		or _differs(ELEMENTS_DATA_PATH, elements_data_text)
		or _differs(FIZZLE_JSON_PATH, fizzle_text)
		or _differs(FIZZLE_TABLE_PATH, fizzle_resource_text)
		or _differs(COMBAT_IDENTITY_PATH, combat_identity_text)
		or _differs(POT_PATH, pot)
		or _po_needs_merge(LOCALE_PO_PATH, item_entries)
	)

	if not check_only:
		DirAccess.make_dir_recursive_absolute(OUT_DIR)
		_write(PROTOTREE_PATH, json_text)
		_write(ITEM_IDS_PATH, ids_text)
		_write(FACTION_IDS_PATH, faction_ids_text)
		_write(NPC_IDS_PATH, npc_ids_text)
		_write(DOM_NPC_ROSTER_PATH, npc_roster_text)
		_write(DOM_NPC_PLACEMENTS_PATH, npc_placements_text)
		DirAccess.make_dir_recursive_absolute(
			ProjectSettings.globalize_path(DOM_NPC_DIALOGUE_PATH.get_base_dir())
		)
		_write(DOM_NPC_DIALOGUE_PATH, npc_dialogue_text)
		_write(ENCOUNTERS_PATH, encounters_text)
		_write(ENCOUNTER_IDS_PATH, encounter_ids_text)
		_write(ELEMENTS_JSON_PATH, elements_text)
		_write(ELEMENTS_DATA_PATH, elements_data_text)
		_write(FIZZLE_JSON_PATH, fizzle_text)
		_write(FIZZLE_TABLE_PATH, fizzle_resource_text)
		_write(COMBAT_IDENTITY_PATH, combat_identity_text)
		_write(POT_PATH, pot)
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://locale"))
		_write(LOCALE_PO_PATH, locale_po)

	return {
		"count": paths.size(),
		"encounter_count": encounter_artifacts["count"],
		"npc_count": npc_artifacts["count"],
		"drift": drift,
	}


static func _npc_artifacts() -> Dictionary:
	var root := _root_by_name("NPCs")
	var faction_root := _root_by_name("Factions")
	var valid_factions := {}
	for faction: PandoraEntity in Pandora.get_all_entities(faction_root):
		if faction is PandoraCategory:
			continue
		var faction_id := faction.get_string("Vault Id")
		if not faction_id.is_empty():
			valid_factions[faction_id] = true

	var rows_by_id := {}
	var placements_by_id := {}
	var display_names := {}
	var quest_involved_count := 0
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		if not entity.has_entity_property("Town Id") or entity.get_string("Town Id") != "dom":
			continue

		var npc_id := entity.get_string("NPC Id")
		var display_name := entity.get_string("Display Name")
		var role := entity.get_string("Role")
		var home := entity.get_string("Home")
		var district := entity.get_string("District")
		var faction_id := entity.get_string("Faction Id")
		var portrait_id := entity.get_string("Portrait Id")
		var portrait_path := entity.get_string("Portrait Path")
		var dialogue_title := "dom_%s" % npc_id.replace("-", "_").replace("/", "_")
		assert(
			StableIdsScript.is_valid(StableIdsScript.ACTOR, npc_id),
			"Dom NPC has invalid stable actor ID: %s" % npc_id
		)
		assert(not rows_by_id.has(npc_id), "Duplicate Dom NPC ID: %s" % npc_id)
		assert(not display_name.is_empty(), "Dom NPC '%s' has no display name" % npc_id)
		assert(not display_names.has(display_name), "Duplicate Dom NPC display name: %s" % display_name)
		assert(not role.is_empty(), "Dom NPC '%s' has no role/trade" % npc_id)
		assert(not home.is_empty(), "Dom NPC '%s' has no home" % npc_id)
		assert(not district.is_empty(), "Dom NPC '%s' has no district" % npc_id)
		assert(
			valid_factions.has(faction_id),
			"Dom NPC '%s' references unknown vault faction '%s'" % [npc_id, faction_id]
		)
		assert(
			StableIdsScript.is_valid(StableIdsScript.ACTOR, portrait_id),
			"Dom NPC '%s' has invalid portrait ID '%s'" % [npc_id, portrait_id]
		)
		assert(
			portrait_path.is_empty() or _is_safe_portrait_path(portrait_path),
			"Dom NPC '%s' has unsafe portrait path '%s'" % [npc_id, portrait_path]
		)
		assert(
			StableIdsScript.is_valid(StableIdsScript.DIALOGUE_NODE, dialogue_title),
			"Dom NPC '%s' has invalid dialogue title" % npc_id
		)

		var hooks: Array[Dictionary] = []
		var hook_values := _parse_json_array(entity.get_string("Quest Hooks"), "Quest Hooks", npc_id)
		for hook_value: Variant in hook_values:
			assert(hook_value is Dictionary, "Dom NPC '%s' has a non-object quest hook" % npc_id)
			var hook: Dictionary = hook_value.duplicate(true)
			var quest_id := str(hook.get("quest_id", ""))
			var involvement := str(hook.get("involvement", ""))
			var state_source := str(hook.get("state_source", ""))
			assert(
				StableIdsScript.is_valid(StableIdsScript.QUEST, quest_id),
				"Dom NPC '%s' has invalid quest-hook ID '%s'" % [npc_id, quest_id]
			)
			assert(
				involvement in QUEST_INVOLVEMENT_TYPES,
				"Dom NPC '%s' has invalid quest involvement '%s'" % [npc_id, involvement]
			)
			assert(not str(hook.get("summary", "")).is_empty(), "Quest hook has no summary")
			if involvement in ["gate", "state_change"]:
				assert(state_source == "GameState", "Quest state gates must use GameState")
				var world_fact_id := str(hook.get("world_fact_id", ""))
				assert(
					StableIdsScript.is_valid(StableIdsScript.WORLD_FACT, world_fact_id),
					"Dom NPC '%s' has invalid world-fact ID" % npc_id
				)
				hook["world_fact_stable_id"] = StableIdsScript.world_fact(world_fact_id)
			elif involvement == "reputation_reaction":
				assert(state_source == "Reputation.band", "Reputation reactions must use Reputation.band")
				assert(hook.get("faction_id", "") == faction_id, "Reaction faction must match affiliation")
				assert(hook.get("band", "") in ["hostile", "cold", "neutral", "warm", "allied"])
			else:
				assert(state_source == "QuestRegistry", "Quest hooks must use QuestRegistry")
			hook["stable_id"] = StableIdsScript.quest(quest_id)
			hooks.append(hook)
		if not hooks.is_empty():
			quest_involved_count += 1

		var placement := {
			"scene": entity.get_string("Placement Scene"),
			"anchor": entity.get_string("Placement Anchor"),
			"offset": [entity.get_float("Placement X"), entity.get_float("Placement Y")],
		}
		assert(FileAccess.file_exists(placement["scene"]), "Missing placement scene for %s" % npc_id)
		assert(not str(placement["anchor"]).is_empty(), "Missing placement anchor for %s" % npc_id)

		var dialogue := {
			"path": DOM_NPC_DIALOGUE_PATH,
			"title": dialogue_title,
			"stable_id": StableIdsScript.dialogue_node(dialogue_title),
			"greeting": entity.get_string("Dialogue Greeting"),
			"context": entity.get_string("Dialogue Context"),
			"farewell": entity.get_string("Dialogue Farewell"),
		}
		_validate_dialogue_text(npc_id, dialogue)
		var portrait := {
			"id": portrait_id,
			"kind": "monogram" if portrait_path.is_empty() else "asset",
			"asset_path": portrait_path,
			"monogram": _portrait_monogram(display_name),
			"mark": npc_id.sha256_text().left(4).to_upper(),
			"palette_index": (npc_id.hash() & 0x7fffffff) % PORTRAIT_VARIANT_COUNT,
		}
		rows_by_id[npc_id] = {
			"id": npc_id,
			"stable_id": StableIdsScript.actor(npc_id),
			"display_name": display_name,
			"role": role,
			"home": home,
			"district": district,
			"faction_id": faction_id,
			"quest_hooks": hooks,
			"portrait": portrait,
			"dialogue": dialogue,
			"placement": placement,
		}
		placements_by_id[npc_id] = placement
		display_names[display_name] = true

	assert(rows_by_id.size() == 60, "Dom roster must contain exactly 60 NPCs")
	assert(quest_involved_count >= 50, "At least 50 Dom NPCs must carry a quest hook")
	var npc_ids: Array = rows_by_id.keys()
	npc_ids.sort()
	var ordered_rows := {}
	var ordered_placements := {}
	for npc_id: String in npc_ids:
		ordered_rows[npc_id] = rows_by_id[npc_id]
		ordered_placements[npc_id] = placements_by_id[npc_id]
	var roster := {
		"town_id": "dom",
		"dialogue_path": DOM_NPC_DIALOGUE_PATH,
		"npcs": ordered_rows,
	}
	var placements := {"town_id": "dom", "placements": ordered_placements}
	return {
		"roster_json": JSON.stringify(roster, "  ", false) + "\n",
		"placements_json": JSON.stringify(placements, "  ", false) + "\n",
		"dialogue": _dom_dialogue_source(ordered_rows),
		"count": ordered_rows.size(),
	}


static func _dom_dialogue_source(rows: Dictionary) -> String:
	var source := ""
	for npc_id: String in rows:
		var row: Dictionary = rows[npc_id]
		var dialogue: Dictionary = row["dialogue"]
		var speaker := str(row["display_name"])
		source += "~ %s\n" % dialogue["title"]
		source += "%s: %s\n" % [speaker, dialogue["greeting"]]
		source += "%s: %s\n" % [speaker, dialogue["context"]]
		source += "%s: %s\n" % [speaker, dialogue["farewell"]]
		source += "=> END\n\n"
	return source.trim_suffix("\n")


static func _validate_dialogue_text(npc_id: String, dialogue: Dictionary) -> void:
	for field: String in ["greeting", "context", "farewell"]:
		var line := str(dialogue.get(field, ""))
		assert(not line.is_empty(), "Dom NPC '%s' has empty dialogue %s" % [npc_id, field])
		assert(line != "...", "Dom NPC '%s' has empty placeholder dialogue" % npc_id)
		assert(not "\n" in line and not "\r" in line, "Dialogue lines must be single-line")
		assert(not "=>" in line and not line.begins_with("~"), "Dialogue line contains syntax")


static func _portrait_monogram(display_name: String) -> String:
	var parts := display_name.split(" ", false)
	if parts.is_empty():
		return "?"
	if parts.size() == 1:
		return parts[0].left(2).to_upper()
	return (parts[0].left(1) + parts[-1].left(1)).to_upper()


static func _is_safe_portrait_path(path: String) -> bool:
	return (
		path.begins_with("res://")
		and not ".." in path
		and path.get_extension().to_lower() in SAFE_PORTRAIT_EXTENSIONS
	)


static func _item_entries(protos: Dictionary, paths: Array) -> Array[Dictionary]:
	var entries: Array[Dictionary] = []
	for p: String in paths:
		var key_base := p.to_upper().replace("/", "_").replace("-", "_")
		entries.append(
			{
				"key": "ITEM_%s_NAME" % key_base,
				"path": p,
				"field": "display name",
				"source": str(protos[p]["name"]),
			}
		)
		entries.append(
			{
				"key": "ITEM_%s_DESC" % key_base,
				"path": p,
				"field": "description",
				"source": str(protos[p]["description"]),
			}
		)
	return entries


static func _build_pot(entries: Array[Dictionary]) -> String:
	var pot := _po_header("")
	for entry: Dictionary in entries:
		pot += _po_entry(entry, "", false)
	return pot


static func _merge_locale_po(path: String, entries: Array[Dictionary]) -> String:
	var existing := _read_po_entries(path)
	var po := _po_header(LOCALE_CODE)
	for entry: Dictionary in entries:
		var key: String = entry["key"]
		var previous: Dictionary = existing.get(key, {})
		var translation := str(previous.get("translation", ""))
		var source_changed := (
			previous.has("source") and str(previous["source"]) != str(entry["source"])
		)
		var fuzzy := bool(previous.get("fuzzy", false)) or source_changed
		po += _po_entry(entry, translation, fuzzy)
	return po.trim_suffix("\n").trim_suffix("\n") + "\n"


static func _po_needs_merge(path: String, entries: Array[Dictionary]) -> bool:
	var existing := _read_po_entries(path)
	for entry: Dictionary in entries:
		var key: String = entry["key"]
		if not existing.has(key):
			return true
		if str(existing[key].get("source", "")) != str(entry["source"]):
			return true
	return false


static func _po_header(language: String) -> String:
	var header := (
		"# %s\n# %s\nmsgid \"\"\nmsgstr \"\"\n"
		% [GENERATED_HEADER, GENERATED_INSTRUCTION]
	)
	header += '"Project-Id-Version: SoulMeter\\n"\n'
	header += '"Content-Type: text/plain; charset=UTF-8\\n"\n'
	if not language.is_empty():
		header += '"Language: %s\\n"\n' % language
	header += "\n"
	return header


static func _po_entry(entry: Dictionary, translation: String, fuzzy: bool) -> String:
	var row := (
		"#. %s — %s\n#. English source: %s\n"
		% [entry["path"], entry["field"], str(entry["source"]).replace("\n", " ")]
	)
	if fuzzy:
		row += "#, fuzzy\n"
	row += 'msgid "%s"\nmsgstr "%s"\n\n' % [entry["key"], _po_escape(translation)]
	return row


static func _read_po_entries(path: String) -> Dictionary:
	var result := {}
	if not FileAccess.file_exists(path):
		return result
	var text := FileAccess.get_file_as_string(path)
	for block: String in text.split("\n\n", false):
		var key := _po_field(block, "msgid")
		if key.is_empty():
			continue
		var source := ""
		for line: String in block.split("\n"):
			var marker := "#. English source: "
			if line.begins_with(marker):
				source = _po_unescape(line.trim_prefix(marker))
				break
		result[key] = {
			"source": source,
			"translation": _po_field(block, "msgstr"),
			"fuzzy": block.contains("#, fuzzy"),
		}
	return result


static func _po_field(block: String, field: String) -> String:
	var value := ""
	var reading := false
	for line: String in block.split("\n"):
		if line.begins_with(field + " "):
			value = _po_unescape(line.substr(field.length()).strip_edges())
			reading = true
		elif reading and line.begins_with("\""):
			value += _po_unescape(line.strip_edges())
		elif reading:
			break
	return value


static func _po_unescape(value: String) -> String:
	var stripped := value.strip_edges()
	if not stripped.begins_with("\""):
		return stripped
	var parsed: Variant = JSON.parse_string(stripped)
	return str(parsed) if parsed is String else stripped.trim_prefix("\"").trim_suffix("\"")


static func _encounter_artifacts() -> Dictionary:
	var combatants_root := _root_by_name("Combatants")
	var encounters_root := _root_by_name("Encounters")
	var combatants := {}
	for entity: PandoraEntity in Pandora.get_all_entities(combatants_root):
		if entity is PandoraCategory:
			continue
		var combatant_id := entity.get_string("Combatant Id")
		assert(not combatant_id.is_empty(), "Combatant is missing Combatant Id")
		assert(not combatants.has(combatant_id), "Duplicate combatant ID: %s" % combatant_id)
		var affinity := entity.get_integer("Balance Affinity")
		assert(affinity >= -1 and affinity <= 1, "Invalid Balance Affinity: %s" % combatant_id)
		combatants[combatant_id] = {
			"id": combatant_id,
			"display_name": entity.get_string("Display Name"),
			"max_hp": entity.get_integer("Max HP"),
			"attack": entity.get_integer("Attack"),
			"defense": entity.get_integer("Defense"),
			"balance_affinity": affinity,
			"balance_pressure": entity.get_integer("Balance Pressure"),
		}

	var encounters := {}
	for entity: PandoraEntity in Pandora.get_all_entities(encounters_root):
		if entity is PandoraCategory:
			continue
		var encounter_id := entity.get_string("Encounter Id")
		assert(not encounter_id.is_empty(), "Encounter is missing Encounter Id")
		assert(not encounters.has(encounter_id), "Duplicate encounter ID: %s" % encounter_id)
		var enemies: Array[Dictionary] = []
		for combatant_id in _split_ids(entity.get_string("Combatant Ids")):
			assert(
				combatants.has(combatant_id),
				"Encounter '%s' references unknown combatant '%s'" % [encounter_id, combatant_id]
			)
			enemies.append(combatants[combatant_id].duplicate(true))
		assert(not enemies.is_empty(), "Encounter has no combatants: %s" % encounter_id)
		encounters[encounter_id] = {
			"display_name": entity.get_string("Display Name"),
			"composition": _parse_json_object(entity.get_string("Composition"), "Composition", encounter_id),
			"zone_layout": _parse_json_array(entity.get_string("Zone Layout"), "Zone Layout", encounter_id),
			"balance_bias": entity.get_float("Balance Bias"),
			"speech_hooks": _parse_json_array(entity.get_string("Speech Hooks"), "Speech Hooks", encounter_id),
			"defeated_flag": entity.get_string("Defeated Flag"),
			"win_faction": entity.get_string("Win Faction"),
			"win_delta": entity.get_float("Win Delta"),
			"win_cause": entity.get_string("Win Cause"),
			"loss_faction": entity.get_string("Loss Faction"),
			"loss_delta": entity.get_float("Loss Delta"),
			"loss_cause": entity.get_string("Loss Cause"),
			"default_outcome": entity.get_string("Default Outcome"),
			"context_actions":
			_parse_json_array(
				entity.get_string("Context Actions"), "Context Actions", encounter_id
			),
			"outcomes": _parse_json_object(entity.get_string("Outcomes"), "Outcomes", encounter_id),
			"enemies": enemies,
		}

	var encounter_ids: Array = encounters.keys()
	encounter_ids.sort()
	var ordered := {}
	for encounter_id in encounter_ids:
		ordered[encounter_id] = encounters[encounter_id]
	return {
		"json": JSON.stringify(ordered, "  ", false) + "\n",
		"ids": _ids_source("EncounterIds", encounter_ids),
		"count": encounter_ids.size(),
	}


static func _combat_identity_artifact() -> String:
	var balance_root := _root_by_name("Balance Bands")
	var weakness_root := _root_by_name("Defining Weaknesses")
	var combatants_root := _root_by_name("Combatants")
	var combatant_ids := {}
	for entity: PandoraEntity in Pandora.get_all_entities(combatants_root):
		if entity is PandoraCategory:
			continue
		var combatant_id := entity.get_string("Combatant Id")
		assert(not combatant_id.is_empty(), "Combatant is missing Combatant Id")
		combatant_ids[combatant_id] = true

	var bands: Array[Dictionary] = []
	var band_ids := {}
	for entity: PandoraEntity in Pandora.get_all_entities(balance_root):
		if entity is PandoraCategory:
			continue
		var band_id := entity.get_string("Band Id")
		assert(not band_id.is_empty(), "Balance band is missing Band Id")
		assert(not band_ids.has(band_id), "Duplicate balance band ID: %s" % band_id)
		band_ids[band_id] = true
		var minimum := entity.get_integer("Minimum")
		var maximum := entity.get_integer("Maximum")
		assert(minimum <= maximum, "Balance band '%s' has an inverted range" % band_id)
		bands.append({
			"id": band_id,
			"display_name": entity.get_string("Display Name"),
			"minimum": minimum,
			"maximum": maximum,
			"global": entity.get_bool("Global"),
			"effects": _parse_json_object_value(
				entity.get_string("Effect Parameters"), "Effect Parameters", band_id
			),
			"tunable": entity.get_bool("Tunable"),
		})
	bands.sort_custom(
		func(a: Dictionary, b: Dictionary) -> bool: return int(a["minimum"]) < int(b["minimum"])
	)
	assert(not bands.is_empty(), "Pandora has no Balance Bands")
	for index in range(1, bands.size()):
		assert(
			int(bands[index - 1]["maximum"]) + 1 == int(bands[index]["minimum"]),
			"Balance bands must cover a contiguous integer range"
		)

	var archetypes := {}
	for entity: PandoraEntity in Pandora.get_all_entities(weakness_root):
		if entity is PandoraCategory:
			continue
		var archetype_id := entity.get_string("Archetype Id")
		var weakness_id := entity.get_string("Weakness Id")
		var check_skill := entity.get_string("Check Skill")
		var effect_id := entity.get_string("Effect Id")
		assert(combatant_ids.has(archetype_id), "Unknown weakness archetype: %s" % archetype_id)
		assert(not weakness_id.is_empty() and not " " in weakness_id, "Invalid weakness ID")
		assert(check_skill in ["lore", "insight"], "Invalid Defining Strike skill: %s" % check_skill)
		assert(
			effect_id in ["cripple", "disarm", "bind_break", "reveal"],
			"Invalid Defining Strike effect: %s" % effect_id
		)
		var rows: Array = archetypes.get(archetype_id, [])
		rows.append({
			"id": weakness_id,
			"display_name": entity.get_string("Display Name"),
			"check_skill": check_skill,
			"check_modifier": entity.get_float("Check Modifier"),
			"lore_minimum": entity.get_float("Lore Minimum"),
			"prior_encounters": entity.get_integer("Prior Encounters"),
			"effect_id": effect_id,
			"effect_parameters": _parse_json_object_value(
				entity.get_string("Effect Parameters"), "Effect Parameters", weakness_id
			),
			"resistance": {
				"stat": entity.get_string("Resistance Stat"),
				"threshold": entity.get_integer("Resistance Threshold"),
			},
		})
		archetypes[archetype_id] = rows
	for combatant_id: String in combatant_ids:
		assert(archetypes.has(combatant_id), "Combatant has no Defining Strike table: %s" % combatant_id)

	var ordered_archetypes := {}
	var archetype_ids: Array = archetypes.keys()
	archetype_ids.sort()
	for archetype_id: String in archetype_ids:
		var rows: Array = archetypes[archetype_id]
		rows.sort_custom(
			func(a: Dictionary, b: Dictionary) -> bool: return str(a["id"]) < str(b["id"])
		)
		ordered_archetypes[archetype_id] = rows
	var data := {
		"balance": {
			"minimum": bands[0]["minimum"],
			"maximum": bands[-1]["maximum"],
			"bands": bands,
		},
		"defining_strikes": {"archetypes": ordered_archetypes},
	}
	return JSON.stringify(data, "  ", false) + "\n"


static func _element_artifacts() -> Dictionary:
	var elements_root := _root_by_name("Elements")
	var triads_root := _root_by_name("Triads")
	var impositions_root := _root_by_name("Impositions")
	var rule_bends_root := _root_by_name("Rule-Bends")
	var breadth_root := _root_by_name("Breadth")
	var magnitude_root := _root_by_name("Magnitude")
	var elements_by_id := {}
	for entity: PandoraEntity in Pandora.get_all_entities(elements_root):
		if entity is PandoraCategory:
			continue
		var element_id := entity.get_string("Element Id")
		assert(not element_id.is_empty(), "Element is missing Element Id")
		elements_by_id[element_id] = {
			"id": element_id,
			"display_name": entity.get_string("Display Name"),
			"vault_id": entity.get_string("Vault Id"),
			"imposition_id": entity.get_string("Imposition Id"),
			"imposition_display_name": entity.get_string("Imposition Display Name"),
			"rule_bend_id": entity.get_string("Rule Bend Id"),
			"rule_bend_description": entity.get_string("Rule Bend Description"),
			"deals_damage": entity.get_bool("Deals Damage"),
		}
	var elements: Array[Dictionary] = []
	for element_id: String in ELEMENT_ORDER:
		assert(elements_by_id.has(element_id), "Missing element: %s" % element_id)
		elements.append(elements_by_id[element_id])

	var triads_by_id := {}
	for entity: PandoraEntity in Pandora.get_all_entities(triads_root):
		if entity is PandoraCategory:
			continue
		var triad_id := entity.get_string("Triad Id")
		var parameters := _parse_json_object_value(entity.get_string("Unique Effect Parameters"), "Unique Effect Parameters", triad_id)
		triads_by_id[triad_id] = {
			"id": triad_id,
			"display_name": entity.get_string("Display Name"),
			"vault_id": entity.get_string("Vault Id"),
			"elements": entity.get_string("Elements").split(",", false),
			"center": entity.get_string("Center"),
			"unique_effect": {
				"id": entity.get_string("Unique Effect Id"),
				"display_name": entity.get_string("Unique Effect Display Name"),
				"parameters": parameters,
			},
		}
	var triads: Array[Dictionary] = []
	for triad_id: String in TRIAD_ORDER:
		assert(triads_by_id.has(triad_id), "Missing triad: %s" % triad_id)
		triads.append(triads_by_id[triad_id])

	var data := {
		"elements": elements,
		"triads": triads,
		"impositions": _simple_definition_rows(impositions_root, "Imposition Id"),
		"rule_bends": _rule_bend_rows(rule_bends_root),
		"breadths": _breadth_rows(breadth_root),
		"magnitudes": _magnitude_rows(magnitude_root),
	}
	return {"json": JSON.stringify(data, "  ", false) + "\n", "gd": _elements_data_source(elements, triads)}


static func _simple_definition_rows(root: PandoraCategory, id_property: String) -> Array[Dictionary]:
	var rows: Array[Dictionary] = []
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		rows.append({"id": entity.get_string(id_property), "display_name": entity.get_string("Display Name"), "vault_id": entity.get_string("Vault Id")})
	rows.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return a["id"] < b["id"])
	return rows


static func _rule_bend_rows(root: PandoraCategory) -> Array[Dictionary]:
	var rows: Array[Dictionary] = []
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		rows.append({"id": entity.get_string("Rule Bend Id"), "display_name": entity.get_string("Display Name"), "description": entity.get_string("Description"), "vault_id": entity.get_string("Vault Id")})
	rows.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return a["id"] < b["id"])
	return rows


static func _breadth_rows(root: PandoraCategory) -> Array[Dictionary]:
	var rows: Array[Dictionary] = []
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		rows.append({"id": entity.get_string("Breadth Id"), "display_name": entity.get_string("Display Name"), "element_count": entity.get_integer("Element Count"), "fizzle_add": entity.get_float("Fizzle Add"), "vault_id": entity.get_string("Vault Id")})
	rows.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return a["id"] < b["id"])
	return rows


static func _magnitude_rows(root: PandoraCategory) -> Array[Dictionary]:
	var rows: Array[Dictionary] = []
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		rows.append({"id": entity.get_string("Magnitude Id"), "display_name": entity.get_string("Display Name"), "multiplier": entity.get_float("Multiplier"), "vault_id": entity.get_string("Vault Id")})
	rows.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return a["id"] < b["id"])
	return rows


static func _fizzle_artifacts() -> Dictionary:
	var root := _root_by_name("Fizzle Tables")
	var table: PandoraEntity = null
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if not entity is PandoraCategory and entity.get_string("Table Id") == "default":
			table = entity
			break
	assert(table != null, "Pandora has no default fizzle table")
	var breadth_add := _parse_json_object_value(table.get_string("Breadth Add"), "Breadth Add", "default")
	var strain_add := _parse_json_object_value(table.get_string("Strain Add"), "Strain Add", "default")
	var magnitude_multiplier := _parse_json_object_value(table.get_string("Magnitude Multiplier"), "Magnitude Multiplier", "default")
	var data := {"vault_id": table.get_string("Vault Id"), "breadth_add": breadth_add, "strain_add": strain_add, "magnitude_multiplier": magnitude_multiplier}
	return {"json": JSON.stringify(data, "  ", false) + "\n", "tres": _fizzle_resource_source(breadth_add, strain_add, magnitude_multiplier)}


static func _parse_json_object_value(value: String, field: String, row_id: String) -> Dictionary:
	var parsed: Variant = JSON.parse_string(value)
	assert(parsed is Dictionary, "'%s' has invalid JSON on '%s'" % [field, row_id])
	return parsed


static func _fizzle_resource_source(breadth_add: Dictionary, strain_add: Dictionary, magnitude_multiplier: Dictionary) -> String:
	var source := "; %s\n; %s\n[gd_resource type=\"Resource\" script_class=\"FizzleTable\" load_steps=2 format=3]\n\n" % [GENERATED_HEADER, GENERATED_INSTRUCTION]
	source += "[ext_resource type=\"Script\" path=\"res://globals/fizzle_table.gd\" id=\"1_fizzle\"]\n\n[resource]\nscript = ExtResource(\"1_fizzle\")\n"
	source += "breadth_add = {\n"
	var breadth_keys := ["chord", "tone", "triad"]
	for index: int in breadth_keys.size():
		var key: String = breadth_keys[index]
		var comma := "," if index < breadth_keys.size() - 1 else ""
		source += '\"%s\": %s%s\n' % [key, _gd_number(float(breadth_add.get(key, 0.0))), comma]
	source += "}\nstrain_add = {\n"
	var strain_keys := ["0", "1", "2", "3", "4"]
	for index: int in strain_keys.size():
		var key: String = strain_keys[index]
		var comma := "," if index < strain_keys.size() - 1 else ""
		source += '\t\"%s\": %s%s\n' % [key, _gd_number(float(strain_add.get(key, 0.0))), comma]
	source += "}\nmagnitude_multiplier = {\n"
	var magnitude_keys := ["note", "phrase", "refrain", "song"]
	for index: int in magnitude_keys.size():
		var key: String = magnitude_keys[index]
		var comma := "," if index < magnitude_keys.size() - 1 else ""
		source += '\"%s\": %s%s\n' % [key, _gd_number(float(magnitude_multiplier.get(key, 0.0))), comma]
	source += "}\n"
	return source


static func _elements_data_source(elements: Array[Dictionary], triads: Array[Dictionary]) -> String:
	var source := "# %s\n# %s\nclass_name ElementsData\nextends RefCounted\n\n" % [GENERATED_HEADER, GENERATED_INSTRUCTION]
	source += "const ELEMENT_ROWS: Array[Dictionary] = [\n"
	for row: Dictionary in elements:
		source += "\t%s,\n" % _gd_element_row(row)
	source += "]\n\nconst TRIAD_ROWS: Array[Dictionary] = [\n"
	for row: Dictionary in triads:
		source += "\t%s,\n" % _gd_triad_row(row)
	source += "]\n\n"
	source += """## Definitions are built once and reused. ElementDefinition and TriadDefinition
## are read-only value objects, so sharing an instance is safe — but that makes
## it an INVARIANT: never mutate a definition returned from here. Mutating one
## would corrupt every other caller. (Optimization from PR #109, implemented in
## the generator so it survives regeneration.)
static var _cache_built := false
static var _elements_by_id: Dictionary = {}
static var _triads_by_id: Dictionary = {}
static var _all_elements: Array[ElementDefinition] = []
static var _all_triads: Array[TriadDefinition] = []


static func _build_cache() -> void:
	if _cache_built:
		return
	_elements_by_id.clear()
	_all_elements.clear()
	for row: Dictionary in ELEMENT_ROWS:
		var element_definition := ElementDefinition.from_row(row)
		_elements_by_id[element_definition.id] = element_definition
		_all_elements.append(element_definition)
	_triads_by_id.clear()
	_all_triads.clear()
	for row: Dictionary in TRIAD_ROWS:
		var triad_definition := TriadDefinition.from_row(row)
		_triads_by_id[triad_definition.id] = triad_definition
		_all_triads.append(triad_definition)
	_cache_built = true


static func element(element_id: Variant) -> ElementDefinition:
	_build_cache()
	var requested := ElementWheel.normalize(element_id)
	var cached: Variant = _elements_by_id.get(requested)
	if cached != null:
		return cached
	return ElementDefinition.new()


static func all_elements() -> Array[ElementDefinition]:
	_build_cache()
	return _all_elements.duplicate()


static func triad(triad_id: Variant) -> TriadDefinition:
	_build_cache()
	var requested := ElementWheel.normalize(triad_id)
	var cached: Variant = _triads_by_id.get(requested)
	if cached != null:
		return cached
	return TriadDefinition.new()


static func all_triads() -> Array[TriadDefinition]:
	_build_cache()
	return _all_triads.duplicate()


static func triad_for_elements(elements: Array[StringName]) -> TriadDefinition:
	_build_cache()
	for candidate in _all_triads:
		if candidate.elements.size() != elements.size():
			continue
		var matches := true
		for element in elements:
			if not candidate.elements.has(element):
				matches = false
				break
		if matches:
			return candidate
	return TriadDefinition.new()
"""
	return source


static func _gd_element_row(row: Dictionary) -> String:
	return '{"id": %s, "display_name": %s, "imposition_id": %s, "imposition_display_name": %s, "rule_bend_id": %s, "rule_bend_description": %s, "deals_damage": %s}' % [
		_gd_name(row["id"]), _gd_string(row["display_name"]), _gd_name(row["imposition_id"]), _gd_string(row["imposition_display_name"]), _gd_name(row["rule_bend_id"]), _gd_string(row["rule_bend_description"]), str(row["deals_damage"]).to_lower()
	]


static func _gd_triad_row(row: Dictionary) -> String:
	var element_values: Array[String] = []
	for element_id: String in row["elements"]:
		element_values.append(_gd_name(element_id))
	var effect: Dictionary = row["unique_effect"]
	return '{"id": %s, "display_name": %s, "elements": [%s], "center": %s, "unique_effect": {"id": %s, "display_name": %s, "parameters": %s}}' % [
		_gd_name(row["id"]), _gd_string(row["display_name"]), ", ".join(element_values), _gd_name(row["center"]), _gd_name(effect["id"]), _gd_string(effect["display_name"]), _gd_variant(effect["parameters"])
	]


static func _gd_variant(value: Variant) -> String:
	if value is Dictionary:
		var entries: Array[String] = []
		for key: String in value:
			entries.append("%s: %s" % [_gd_string(key), _gd_variant(value[key])])
		return "{" + ", ".join(entries) + "}"
	if value is Array:
		var entries: Array[String] = []
		for item: Variant in value:
			entries.append(_gd_variant(item))
		return "[" + ", ".join(entries) + "]"
	if value is String:
		return _gd_string(value)
	if value is bool:
		return str(value).to_lower()
	return str(value)


static func _gd_name(value: String) -> String:
	return "&" + _gd_string(value)


static func _gd_string(value: String) -> String:
	return JSON.stringify(value)


static func _gd_number(value: float) -> String:
	return str(value)


static func _root_by_name(root_name: String) -> PandoraCategory:
	for root in Pandora.get_all_roots():
		if root.get_entity_name() == root_name:
			return root
	assert(false, "Pandora has no %s root" % root_name)
	return null


static func _split_ids(value: String) -> PackedStringArray:
	var result := PackedStringArray()
	for part in value.split(",", false):
		var id := part.strip_edges()
		if not id.is_empty():
			result.append(id)
	return result


static func _parse_json_array(value: String, field: String, encounter_id: String) -> Array:
	if value.is_empty():
		return []
	var parsed: Variant = JSON.parse_string(value)
	assert(parsed is Array, "Encounter '%s' has invalid %s JSON" % [encounter_id, field])
	return parsed


static func _parse_json_object(value: String, field: String, encounter_id: String) -> Dictionary:
	if value.is_empty():
		return {}
	var parsed: Variant = JSON.parse_string(value)
	assert(parsed is Dictionary, "Encounter '%s' has invalid %s JSON" % [encounter_id, field])
	return parsed


static func _ids_source(generated_class_name: String, ids: Array) -> String:
	var source := (
		"# %s\n# %s\nclass_name %s\n\n"
		% [GENERATED_HEADER, GENERATED_INSTRUCTION, generated_class_name]
	)
	for id: String in ids:
		source += 'const %s := "%s"\n' % [id.to_upper().replace("-", "_"), id]
	return source


static func _npc_ids_source() -> String:
	var root := _root_by_name("NPCs")
	var unique_ids := {}
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		var npc_id := entity.get_string("NPC Id") if entity.has_entity_property("NPC Id") else ""
		if npc_id.is_empty() and entity.has_entity_property("Vault Id"):
			npc_id = entity.get_string("Vault Id")
		if npc_id.is_empty():
			npc_id = _slug(entity.get_entity_name()).replace("_", "-")
		assert(
			StableIdsScript.is_valid(StableIdsScript.ACTOR, npc_id),
			"NPC has invalid stable actor ID: %s" % npc_id
		)
		assert(not unique_ids.has(npc_id), "Duplicate NPC stable actor ID: %s" % npc_id)
		unique_ids[npc_id] = true
	var ids: Array = unique_ids.keys()
	ids.sort()
	return _ids_source("NpcIds", ids)


static func _vault_ids_source(root_name: String, generated_class_name: String) -> String:
	var root := _root_by_name(root_name)
	var unique_ids := {}
	for entity: PandoraEntity in Pandora.get_all_entities(root):
		if entity is PandoraCategory:
			continue
		var vault_id := (
			entity.get_string("Vault Id") if entity.has_entity_property("Vault Id") else ""
		)
		if vault_id.is_empty():
			vault_id = _slug(entity.get_entity_name()).replace("_", "-")
		if not vault_id.is_empty():
			unique_ids[vault_id] = true
	var ids: Array = unique_ids.keys()
	ids.sort()
	return _ids_source(generated_class_name, ids)


static func _slug(name: String) -> String:
	var s := name.to_lower()
	for pair in [["'", ""], ["’", ""], [" ", "_"], ["-", "_"]]:
		s = s.replace(pair[0], pair[1])
	return s


static func _po_escape(s: String) -> String:
	return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


static func _write(path: String, text: String) -> void:
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string(text)
	f.close()


static func _differs(path: String, text: String) -> bool:
	if not FileAccess.file_exists(path):
		return true
	return FileAccess.get_file_as_string(path) != text
