extends Node
## render_isometric_sprites.gd — one-way Kenney 3D -> 2D isometric art generator.
##
## The runtime game never loads the GLBs. This temporary autoload renders every
## vendored model into a transparent PNG, then emits a ground TileSet and a
## manifest used by the headless drift check.
##
## Camera contract (do not tune per model):
##   - yaw: 45 degrees
##   - pitch: atan(0.5), the 64x32 dimetric angle
##   - orthographic projection
##   - one Kenney model unit == one 64x32 world tile
##
## Run with scripts/render_isometric_sprites.sh. Drift-only runs set
## SOUL_METER_DRIFT_CHECK=1 and never ask the headless renderer for pixels.

const OUTPUT_ROOT := "res://assets/generated/sprites"
const MANIFEST_PATH := OUTPUT_ROOT + "/manifest.json"
const CATALOG_PATH := OUTPUT_ROOT + "/isometric_sprite_catalog.gd"
const GROUND_DIR := OUTPUT_ROOT + "/ground"
const GROUND_ATLAS_PATH := GROUND_DIR + "/ground_tiles.png"
const GROUND_TILESET_PATH := GROUND_DIR + "/ground_tileset.tres"
const GENERATOR_PATH := "res://tools/render_isometric_sprites.gd"

const GENERATED_HEADER := (
	"GENERATED by tools/render_isometric_sprites.gd from assets/kenney3d — DO NOT EDIT."
)
const GENERATED_INSTRUCTION := "Change the source model or generator and regenerate."
const GENERATOR_VERSION := 1

const TILE_SIZE := Vector2i(64, 32)
const WORLD_UNITS_PER_TILE := 1.0
const CAMERA_YAW_DEGREES := 45.0
const CAMERA_PITCH_RADIANS := atan(0.5)
const CAMERA_PITCH_DEGREES := rad_to_deg(CAMERA_PITCH_RADIANS)
const CAMERA_PROJECTION := Camera3D.PROJECTION_ORTHOGONAL
const SPRITE_SIZE := Vector2i(256, 256)
const PIXELS_PER_WORLD_UNIT := float(TILE_SIZE.x) / sqrt(2.0)
const ORTHOGRAPHIC_SIZE := float(SPRITE_SIZE.y) / PIXELS_PER_WORLD_UNIT
const CAMERA_TARGET_Y := 1.25
const CAMERA_DISTANCE := 10.0
const SPRITE_PIVOT_OFFSET := Vector2(
	0.0,
	-CAMERA_TARGET_Y * cos(CAMERA_PITCH_RADIANS) * PIXELS_PER_WORLD_UNIT
)

const KIT_ORDER := ["fantasy-town-kit", "nature-kit", "castle-kit"]
const KIT_SOURCE_DIRS := {
	"fantasy-town-kit": "res://assets/kenney3d/fantasy-town-kit/Models/GLB format",
	"nature-kit": "res://assets/kenney3d/nature-kit/Models/GLTF format",
	"castle-kit": "res://assets/kenney3d/castle-kit/Models/GLB format",
}
const GROUND_TILES := [
	{"name": "grass", "model": "ground_grass"},
	{"name": "dirt", "model": "ground_pathTile"},
	{"name": "stone", "model": "platform_stone"},
	{"name": "road", "model": "ground_pathStraight"},
]


func _ready() -> void:
	await get_tree().process_frame
	if OS.get_environment("SOUL_METER_DRIFT_CHECK") == "1":
		var drift_result := check_drift()
		if drift_result["drift"]:
			printerr(
				"ISO-SPRITE-GEN: DRIFT — committed sprites differ from the source models."
			)
			var errors: PackedStringArray = drift_result["errors"]
			for index in mini(errors.size(), 12):
				printerr("ISO-SPRITE-GEN: " + errors[index])
			get_tree().quit(1)
			return
		print("ISO-SPRITE-GEN: no drift. %d sprites verified." % drift_result["count"])
		get_tree().quit()
		return

	var result: Dictionary = await generate()
	if not result["ok"]:
		printerr("ISO-SPRITE-GEN: FAILED — " + str(result["error"]))
		get_tree().quit(1)
		return
	print(
		"ISO-SPRITE-GEN: complete. %d sprites verified; %d artifacts changed."
		% [result["count"], result["changed"]]
	)
	get_tree().quit()


## Renders all 572 models with one camera and writes deterministic artifacts.
func generate() -> Dictionary:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUTPUT_ROOT))
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(GROUND_DIR))

	var viewport := _create_render_viewport()
	var stage := viewport.get_node("Stage") as Node3D
	var changed_count := 0
	var rendered_count := 0
	var kit_records := {}

	for kit: String in KIT_ORDER:
		var output_dir := OUTPUT_ROOT + "/" + kit
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(output_dir))
		var records := {}
		for filename: String in _model_filenames(KIT_SOURCE_DIRS[kit]):
			var model_name := filename.trim_suffix(".glb")
			var source_path: String = KIT_SOURCE_DIRS[kit] + "/" + filename
			var output_path := output_dir + "/" + model_name + ".png"
			var render_result: Dictionary = await _render_model(
				viewport, stage, source_path, output_path
			)
			if not render_result["ok"]:
				viewport.queue_free()
				return render_result
			changed_count += int(render_result["changed"])
			rendered_count += 1
			records[model_name] = {
				"source": source_path,
				"source_sha256": FileAccess.get_sha256(source_path),
				"output": output_path,
				"output_sha256": FileAccess.get_sha256(output_path),
			}
		kit_records[kit] = records

	viewport.queue_free()
	var ground_result := _write_ground_atlas()
	if not ground_result["ok"]:
		return ground_result
	changed_count += int(ground_result["changed"])

	var tileset_text := _ground_tileset_text()
	changed_count += int(_write_text_if_changed(GROUND_TILESET_PATH, tileset_text))
	var catalog_text := _catalog_text()
	changed_count += int(_write_text_if_changed(CATALOG_PATH, catalog_text))

	var manifest := {
		"_generated": GENERATED_HEADER,
		"instruction": GENERATED_INSTRUCTION,
		"generator_version": GENERATOR_VERSION,
		"generator_sha256": FileAccess.get_sha256(GENERATOR_PATH),
		"camera": {
			"projection": "orthographic",
			"yaw_degrees": CAMERA_YAW_DEGREES,
			"pitch_degrees": CAMERA_PITCH_DEGREES,
			"pitch_radians": CAMERA_PITCH_RADIANS,
			"transparent_background": true,
			"sprite_size": [SPRITE_SIZE.x, SPRITE_SIZE.y],
			"sprite_pivot_offset": [SPRITE_PIVOT_OFFSET.x, SPRITE_PIVOT_OFFSET.y],
		},
		"scale": {
			"world_units_per_tile": WORLD_UNITS_PER_TILE,
			"tile_size": [TILE_SIZE.x, TILE_SIZE.y],
			"pixels_per_world_unit": PIXELS_PER_WORLD_UNIT,
			"orthographic_size": ORTHOGRAPHIC_SIZE,
		},
		"sprite_count": rendered_count,
		"kits": kit_records,
		"ground": {
			"atlas": GROUND_ATLAS_PATH,
			"atlas_sha256": FileAccess.get_sha256(GROUND_ATLAS_PATH),
			"tileset": GROUND_TILESET_PATH,
			"tileset_sha256": _sha256_bytes(tileset_text.to_utf8_buffer()),
			"tiles": ground_result["tiles"],
		},
		"catalog": {
			"path": CATALOG_PATH,
			"sha256": _sha256_bytes(catalog_text.to_utf8_buffer()),
		},
	}
	var manifest_text := JSON.stringify(manifest, "  ", false) + "\n"
	changed_count += int(_write_text_if_changed(MANIFEST_PATH, manifest_text))

	return {"ok": true, "count": rendered_count, "changed": changed_count}


## Checks source/output hashes and deterministic text resources without rendering.
## This deliberately works headlessly; headless Godot cannot rasterize SubViewports.
static func check_drift() -> Dictionary:
	var errors := PackedStringArray()
	if not FileAccess.file_exists(MANIFEST_PATH):
		errors.append("missing manifest: " + MANIFEST_PATH)
		return {"drift": true, "count": 0, "errors": errors}

	var parsed = JSON.parse_string(FileAccess.get_file_as_string(MANIFEST_PATH))
	if not parsed is Dictionary:
		errors.append("manifest is not valid JSON")
		return {"drift": true, "count": 0, "errors": errors}
	var manifest: Dictionary = parsed
	if manifest.get("_generated", "") != GENERATED_HEADER:
		errors.append("manifest generated header changed")
	if int(manifest.get("generator_version", -1)) != GENERATOR_VERSION:
		errors.append("generator version changed")
	if manifest.get("generator_sha256", "") != FileAccess.get_sha256(GENERATOR_PATH):
		errors.append("generator source changed")

	var expected_paths := {}
	var count := 0
	var kits: Dictionary = manifest.get("kits", {})
	for kit: String in KIT_ORDER:
		var source_dir: String = KIT_SOURCE_DIRS[kit]
		var records: Dictionary = kits.get(kit, {})
		var expected_names := {}
		for filename: String in _model_filenames(source_dir):
			var model_name := filename.trim_suffix(".glb")
			var source_path := source_dir + "/" + filename
			var output_path := OUTPUT_ROOT + "/" + kit + "/" + model_name + ".png"
			expected_names[model_name] = true
			expected_paths[output_path] = true
			count += 1
			if not records.has(model_name):
				errors.append("manifest missing model: %s/%s" % [kit, model_name])
				continue
			var record: Dictionary = records[model_name]
			if record.get("source", "") != source_path:
				errors.append("source path drift: %s/%s" % [kit, model_name])
			if record.get("source_sha256", "") != FileAccess.get_sha256(source_path):
				errors.append("source changed: %s/%s" % [kit, model_name])
			if record.get("output", "") != output_path:
				errors.append("output path drift: %s/%s" % [kit, model_name])
			elif not FileAccess.file_exists(output_path):
				errors.append("missing sprite: %s/%s" % [kit, model_name])
			elif record.get("output_sha256", "") != FileAccess.get_sha256(output_path):
				errors.append("sprite changed: %s/%s" % [kit, model_name])
		for recorded_name: String in records:
			if not expected_names.has(recorded_name):
				errors.append("manifest has removed model: %s/%s" % [kit, recorded_name])

	var recorded_count := int(manifest.get("sprite_count", -1))
	if recorded_count != count:
		errors.append("sprite count changed: manifest=%d source=%d" % [recorded_count, count])
	for kit: String in KIT_ORDER:
		var output_dir := OUTPUT_ROOT + "/" + kit
		for filename: String in _png_filenames(output_dir):
			var output_path := output_dir + "/" + filename
			if not expected_paths.has(output_path):
				errors.append("unexpected generated sprite: " + output_path)

	var expected_tileset := _ground_tileset_text()
	if _text_differs(GROUND_TILESET_PATH, expected_tileset):
		errors.append("ground TileSet changed")
	var expected_catalog := _catalog_text()
	if _text_differs(CATALOG_PATH, expected_catalog):
		errors.append("sprite catalog changed")

	var ground: Dictionary = manifest.get("ground", {})
	if not FileAccess.file_exists(GROUND_ATLAS_PATH):
		errors.append("missing ground atlas")
	elif ground.get("atlas_sha256", "") != FileAccess.get_sha256(GROUND_ATLAS_PATH):
		errors.append("ground atlas changed")
	if ground.get("tileset_sha256", "") != _sha256_bytes(expected_tileset.to_utf8_buffer()):
		errors.append("ground TileSet manifest hash changed")
	var catalog: Dictionary = manifest.get("catalog", {})
	if catalog.get("sha256", "") != _sha256_bytes(expected_catalog.to_utf8_buffer()):
		errors.append("sprite catalog manifest hash changed")

	return {"drift": not errors.is_empty(), "count": count, "errors": errors}


func _create_render_viewport() -> SubViewport:
	var viewport := SubViewport.new()
	viewport.name = "IsometricRenderViewport"
	viewport.size = SPRITE_SIZE
	viewport.transparent_bg = true
	viewport.own_world_3d = true
	viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ALWAYS
	viewport.render_target_update_mode = SubViewport.UPDATE_DISABLED
	viewport.msaa_3d = Viewport.MSAA_4X
	add_child(viewport)

	var stage := Node3D.new()
	stage.name = "Stage"
	viewport.add_child(stage)

	var environment := Environment.new()
	environment.background_mode = Environment.BG_COLOR
	environment.background_color = Color(0.0, 0.0, 0.0, 0.0)
	environment.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	environment.ambient_light_color = Color(0.82, 0.86, 0.92)
	environment.ambient_light_energy = 0.72
	environment.reflected_light_source = Environment.REFLECTION_SOURCE_DISABLED
	var world_environment := WorldEnvironment.new()
	world_environment.environment = environment
	viewport.add_child(world_environment)

	var sunlight := DirectionalLight3D.new()
	sunlight.rotation_degrees = Vector3(-52.0, -38.0, 0.0)
	sunlight.light_color = Color(1.0, 0.92, 0.78)
	sunlight.light_energy = 1.35
	sunlight.shadow_enabled = true
	viewport.add_child(sunlight)

	var camera := Camera3D.new()
	camera.name = "Camera3D"
	camera.projection = CAMERA_PROJECTION
	camera.size = ORTHOGRAPHIC_SIZE
	camera.near = 0.05
	camera.far = 100.0
	var target := Vector3(0.0, CAMERA_TARGET_Y, 0.0)
	var camera_direction := Vector3(
		sin(deg_to_rad(CAMERA_YAW_DEGREES)) * cos(CAMERA_PITCH_RADIANS),
		sin(CAMERA_PITCH_RADIANS),
		cos(deg_to_rad(CAMERA_YAW_DEGREES)) * cos(CAMERA_PITCH_RADIANS)
	)
	var camera_position := target + camera_direction * CAMERA_DISTANCE
	camera.look_at_from_position(camera_position, target, Vector3.UP)
	camera.current = true
	viewport.add_child(camera)
	return viewport


func _render_model(
	viewport: SubViewport, stage: Node3D, source_path: String, output_path: String
) -> Dictionary:
	var packed := ResourceLoader.load(source_path, "PackedScene") as PackedScene
	if packed == null:
		return {"ok": false, "error": "could not load " + source_path}
	var model := packed.instantiate() as Node3D
	if model == null:
		return {"ok": false, "error": "model root is not Node3D: " + source_path}
	_apply_external_colormap(model, source_path)
	var bounds := _model_bounds(model)
	if bounds.size.is_zero_approx():
		model.free()
		return {"ok": false, "error": "model has no mesh bounds: " + source_path}

	var center := bounds.get_center()
	model.position += Vector3(-center.x, -bounds.position.y, -center.z)
	stage.add_child(model)
	await get_tree().process_frame
	viewport.render_target_update_mode = SubViewport.UPDATE_ONCE
	await RenderingServer.frame_post_draw
	var image := viewport.get_texture().get_image()
	stage.remove_child(model)
	model.free()
	if image == null or image.is_empty():
		return {"ok": false, "error": "empty render for " + source_path}
	if image.get_format() != Image.FORMAT_RGBA8:
		image.convert(Image.FORMAT_RGBA8)
	var png_bytes := image.save_png_to_buffer()
	if png_bytes.is_empty():
		return {"ok": false, "error": "PNG encoding failed for " + source_path}
	var changed := _write_bytes_if_changed(output_path, png_bytes)
	return {"ok": true, "changed": changed}


## Fantasy Town and Castle GLBs share an external palette image. Binding it
## explicitly makes output independent of whether Godot's warm scene import was
## produced before or after that dependency arrived in the worktree.
static func _apply_external_colormap(root_node: Node3D, source_path: String) -> void:
	var colormap_path := source_path.get_base_dir() + "/Textures/colormap.png"
	if not FileAccess.file_exists(colormap_path):
		return
	var colormap := ResourceLoader.load(colormap_path, "Texture2D") as Texture2D
	if colormap == null:
		push_error("Could not load external GLB colormap: " + colormap_path)
		return
	var stack: Array[Node] = [root_node]
	while not stack.is_empty():
		var node: Node = stack.pop_back()
		if node is MeshInstance3D:
			var mesh_instance := node as MeshInstance3D
			if mesh_instance.mesh != null:
				for surface_index in mesh_instance.mesh.get_surface_count():
					var source_material := mesh_instance.get_active_material(surface_index)
					if source_material is BaseMaterial3D:
						var material := source_material.duplicate() as BaseMaterial3D
						material.albedo_texture = colormap
						mesh_instance.set_surface_override_material(surface_index, material)
		for child: Node in node.get_children():
			stack.append(child)


static func _model_bounds(root_node: Node3D) -> AABB:
	var points: Array[Vector3] = []
	_accumulate_mesh_points(root_node, Transform3D.IDENTITY, points)
	if points.is_empty():
		return AABB()
	var bounds := AABB(points[0], Vector3.ZERO)
	for index in range(1, points.size()):
		bounds = bounds.expand(points[index])
	return bounds


static func _accumulate_mesh_points(
	node: Node, parent_transform: Transform3D, points: Array[Vector3]
) -> void:
	var node_transform := parent_transform
	if node is Node3D:
		node_transform *= (node as Node3D).transform
	if node is MeshInstance3D:
		var bounds := (node as MeshInstance3D).get_aabb()
		for corner_index in 8:
			points.append(node_transform * bounds.get_endpoint(corner_index))
	for child: Node in node.get_children():
		_accumulate_mesh_points(child, node_transform, points)


static func _write_ground_atlas() -> Dictionary:
	var atlas := Image.create(TILE_SIZE.x * GROUND_TILES.size(), TILE_SIZE.y, false, Image.FORMAT_RGBA8)
	atlas.fill(Color.TRANSPARENT)
	var tile_records: Array[Dictionary] = []
	for index in GROUND_TILES.size():
		var tile: Dictionary = GROUND_TILES[index]
		var sprite_path := (
			OUTPUT_ROOT + "/nature-kit/" + str(tile["model"]) + ".png"
		)
		var source_image := Image.load_from_file(sprite_path)
		if source_image == null or source_image.is_empty():
			return {"ok": false, "error": "could not read ground source " + sprite_path}
		var used_rect := source_image.get_used_rect()
		if used_rect.size == Vector2i.ZERO:
			return {"ok": false, "error": "ground source is transparent " + sprite_path}
		var tile_image := source_image.get_region(used_rect)
		tile_image.resize(TILE_SIZE.x, TILE_SIZE.y, Image.INTERPOLATE_LANCZOS)
		atlas.blit_rect(
			tile_image,
			Rect2i(Vector2i.ZERO, TILE_SIZE),
			Vector2i(index * TILE_SIZE.x, 0)
		)
		tile_records.append(
			{
				"index": index,
				"name": tile["name"],
				"model": tile["model"],
				"atlas_coordinates": [index, 0],
				"source_alpha_rect": [
					used_rect.position.x,
					used_rect.position.y,
					used_rect.size.x,
					used_rect.size.y,
				],
			}
		)
	var png_bytes := atlas.save_png_to_buffer()
	if png_bytes.is_empty():
		return {"ok": false, "error": "ground atlas PNG encoding failed"}
	return {
		"ok": true,
		"changed": _write_bytes_if_changed(GROUND_ATLAS_PATH, png_bytes),
		"tiles": tile_records,
	}


static func _ground_tileset_text() -> String:
	return (
		"; %s\n"
		+ "; %s\n"
		+ "[gd_resource type=\"TileSet\" load_steps=3 format=3]\n\n"
		+ "[ext_resource type=\"Texture2D\" path=\"%s\" id=\"1_ground\"]\n\n"
		+ "[sub_resource type=\"TileSetAtlasSource\" id=\"TileSetAtlasSource_ground\"]\n"
		+ "texture = ExtResource(\"1_ground\")\n"
		+ "texture_region_size = Vector2i(%d, %d)\n"
		+ "0:0/0 = 0\n"
		+ "1:0/0 = 0\n"
		+ "2:0/0 = 0\n"
		+ "3:0/0 = 0\n\n"
		+ "[resource]\n"
		+ "tile_shape = 1\n"
		+ "tile_layout = 5\n"
		+ "tile_size = Vector2i(%d, %d)\n"
		+ "sources/0 = SubResource(\"TileSetAtlasSource_ground\")\n"
	) % [
		GENERATED_HEADER,
		GENERATED_INSTRUCTION,
		GROUND_ATLAS_PATH,
		TILE_SIZE.x,
		TILE_SIZE.y,
		TILE_SIZE.x,
		TILE_SIZE.y,
	]


static func _catalog_text() -> String:
	return (
		"# %s\n"
		+ "# %s\n"
		+ "class_name IsometricSpriteCatalog\n"
		+ "extends RefCounted\n\n"
		+ "const OUTPUT_ROOT := \"%s\"\n"
		+ "const GROUND_TILESET_PATH := \"%s\"\n"
		+ "const TILE_SIZE := Vector2i(%d, %d)\n"
		+ "const WORLD_UNITS_PER_TILE := %.1f\n"
		+ "const CAMERA_YAW_DEGREES := %.1f\n"
		+ "const CAMERA_PITCH_RADIANS := %.12f\n"
		+ "const CAMERA_PITCH_DEGREES := %.12f\n"
		+ "const SPRITE_SIZE := Vector2i(%d, %d)\n"
		+ "const SPRITE_PIVOT_OFFSET := Vector2(%.6f, %.6f)\n\n"
		+ "const GROUND_GRASS := Vector2i(0, 0)\n"
		+ "const GROUND_DIRT := Vector2i(1, 0)\n"
		+ "const GROUND_STONE := Vector2i(2, 0)\n"
		+ "const GROUND_ROAD := Vector2i(3, 0)\n\n"
		+ "static func texture_path(kit: String, model: String) -> String:\n"
		+ "\treturn OUTPUT_ROOT + \"/\" + kit + \"/\" + model + \".png\"\n"
	) % [
		GENERATED_HEADER,
		GENERATED_INSTRUCTION,
		OUTPUT_ROOT,
		GROUND_TILESET_PATH,
		TILE_SIZE.x,
		TILE_SIZE.y,
		WORLD_UNITS_PER_TILE,
		CAMERA_YAW_DEGREES,
		CAMERA_PITCH_RADIANS,
		CAMERA_PITCH_DEGREES,
		SPRITE_SIZE.x,
		SPRITE_SIZE.y,
		SPRITE_PIVOT_OFFSET.x,
		SPRITE_PIVOT_OFFSET.y,
	]


static func _model_filenames(directory: String) -> PackedStringArray:
	var result := PackedStringArray()
	for filename: String in DirAccess.get_files_at(directory):
		if filename.ends_with(".glb"):
			result.append(filename)
	result.sort()
	return result


static func _png_filenames(directory: String) -> PackedStringArray:
	var result := PackedStringArray()
	if not DirAccess.dir_exists_absolute(directory):
		return result
	for filename: String in DirAccess.get_files_at(directory):
		if filename.ends_with(".png"):
			result.append(filename)
	result.sort()
	return result


static func _write_text_if_changed(path: String, value: String) -> bool:
	return _write_bytes_if_changed(path, value.to_utf8_buffer())


static func _write_bytes_if_changed(path: String, value: PackedByteArray) -> bool:
	if FileAccess.file_exists(path) and FileAccess.get_file_as_bytes(path) == value:
		return false
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		push_error("Could not open generated output for writing: " + path)
		return false
	file.store_buffer(value)
	file.close()
	return true


static func _text_differs(path: String, expected: String) -> bool:
	return not FileAccess.file_exists(path) or FileAccess.get_file_as_string(path) != expected


static func _sha256_bytes(value: PackedByteArray) -> String:
	var hashing := HashingContext.new()
	hashing.start(HashingContext.HASH_SHA256)
	hashing.update(value)
	return hashing.finish().hex_encode()
