extends GdUnitTestSuite

func test_resolve_rejects_invalid_magnitude_count_unknown_and_duplicates() -> void:
	var invalid_magnitude := CompositionResolver.resolve([&"suul"], &"verse")
	assert_str(String(invalid_magnitude.failure_id)).is_equal("invalid_magnitude")
	assert_str(String(CompositionResolver.resolve([], &"note").failure_id)).is_equal("invalid_element_count")
	assert_str(String(CompositionResolver.resolve([&"unknown"], &"note").failure_id)).is_equal("unknown_element")
	assert_str(String(CompositionResolver.resolve([&"suul", &"suul"], &"note").failure_id)).is_equal("duplicate_element")

func test_resolve_tone_and_chords_capture_effect_shape() -> void:
	var tone := CompositionResolver.resolve([&"suul"], &"note")
	assert_bool(tone.is_resolved()).is_true()
	assert_str(String(tone.status_id)).is_equal("tone")
	assert_bool(tone.fizzle_requested).is_true()
	var chord := CompositionResolver.resolve([&"suul", &"bloei"], &"phrase")
	assert_str(String(chord.status_id)).is_equal("chord")
	assert_int(chord.distance_steps).is_equal(1)
	var strained := CompositionResolver.resolve([&"suul", &"aqua"], &"song")
	assert_str(String(strained.status_id)).is_equal("strained_chord")
	assert_bool(strained.rejected).is_false()

func test_resolve_opposed_and_clashing_triads_are_rejected() -> void:
	var opposed := CompositionResolver.resolve([&"suul", &"daar"], &"note")
	assert_str(String(opposed.failure_id)).is_equal("opposed_elements")
	assert_bool(opposed.is_opposed()).is_true()
	var clash := CompositionResolver.resolve([&"suul", &"aqua", &"terra"], &"song")
	assert_bool(clash.is_clash()).is_true()
	assert_str(String(clash.failure_id)).is_equal("span_exceeds_two")

func test_casting_context_blocks_resolved_composition_with_gate_metadata() -> void:
	var result := CompositionResolver.resolve([&"suul", &"bloei"], &"phrase", {"harmony": -2})
	assert_bool(result.allowed).is_false()
	assert_str(String(result.failure_id)).is_equal("casting_gate")
	assert_str(String(result.blocked_by)).is_equal("var_harmony")


# ─── (a) Triad composition: every ratified triad composes to its centre ──────
#
# The ten triads and their ratified centres are canon, authored in Pandora and
# surfaced through ElementsData. This test walks ElementsData.all_triads() so a
# regenerated table is exercised automatically — no triad id, member list, or
# centre is ever written out by hand here.


func test_every_ratified_triad_composes_to_its_centre_and_reports_its_id() -> void:
	var triads: Array[TriadDefinition] = ElementsData.all_triads()
	assert_int(triads.size()).is_equal(ElementsData.TRIAD_ROWS.size())
	for triad: TriadDefinition in triads:
		var result: CompositionResult = CompositionResolver.resolve(triad.elements, &"song")
		assert_bool(result.is_resolved()).override_failure_message(
			"Triad '%s' should resolve, got kind %s (failure '%s')"
			% [triad.id, result.kind, result.failure_id]
		).is_true()
		assert_int(result.kind).is_equal(CompositionResult.Kind.TRIAD)
		assert_str(String(result.center_element)).override_failure_message(
			"Triad '%s' centre" % triad.id
		).is_equal(String(triad.center_element))
		assert_str(String(result.unique_effect_id)).is_equal(String(triad.unique_effect_id))
		# The resolver must report WHICH triad it composed. The only triad
		# identity on CompositionResult is unique_effect_id; the triad id is
		# recoverable by round-tripping the members through ElementsData.
		var identified: TriadDefinition = ElementsData.triad_for_elements(result.elements)
		assert_str(String(identified.id)).override_failure_message(
			"Elements %s should identify triad '%s'" % [result.elements, triad.id]
		).is_equal(String(triad.id))


func test_triad_composition_is_order_insensitive() -> void:
	# triad_for_elements matches on membership, so any permutation of the three
	# members must compose to the same triad with the same centre.
	for triad: TriadDefinition in ElementsData.all_triads():
		var reversed: Array[StringName] = triad.elements.duplicate()
		reversed.reverse()
		var result: CompositionResult = CompositionResolver.resolve(reversed, &"note")
		assert_int(result.kind).is_equal(CompositionResult.Kind.TRIAD)
		assert_str(String(result.center_element)).is_equal(String(triad.center_element))
		assert_str(String(result.unique_effect_id)).is_equal(String(triad.unique_effect_id))


# ─── (b) Strained spans: the strain penalty applies at distance 2, 3, 4 ─────
#
# A two-element chord at wheel distance >= 2 is STRAINED: weakened impositions
# and a Vär cost equal to the distance. Distance 1 (adjacent) is a plain CHORD
# with full imposition and no Vär cost. Pairs are generated by walking the
# wheel, never hand-picked.


func test_strained_chords_at_spans_2_3_and_4_carry_the_strain_penalty() -> void:
	for distance: int in [2, 3, 4]:
		for start_index in range(ElementWheel.ORDER.size()):
			var first: StringName = ElementWheel.ORDER[start_index]
			var second: StringName = ElementWheel.ORDER[
				(start_index + distance) % ElementWheel.ORDER.size()
			]
			var result: CompositionResult = CompositionResolver.resolve([first, second], &"phrase")
			assert_int(result.distance_steps).is_equal(distance)
			assert_int(result.kind).override_failure_message(
				"Pair %s|%s at distance %d should be STRAINED_CHORD"
				% [first, second, distance]
			).is_equal(CompositionResult.Kind.STRAINED_CHORD)
			assert_str(String(result.status_id)).is_equal("strained_chord")
			assert_str(String(result.imposition_strength)).is_equal("weakened")
			assert_int(result.var_cost).is_equal(distance)
			assert_bool(result.rejected).is_false()
			# Only members with a non-empty imposition_id impose (khor and nul
			# have none); those that do impose are weakened.
			var expected_entries := 0
			for member: StringName in [first, second]:
				if not ElementsData.element(member).imposition_id.is_empty():
					expected_entries += 1
			assert_int(result.imposition_entries.size()).override_failure_message(
				"Pair %s|%s should produce %d imposition entries"
				% [first, second, expected_entries]
			).is_equal(expected_entries)
			for entry: Dictionary in result.imposition_entries:
				assert_str(String(entry["strength"])).is_equal("weakened")
				assert_bool([first, second].has(StringName(entry["element"]))).override_failure_message(
					"Imposition entry element '%s' should be one of %s|%s"
					% [entry["element"], first, second]
				).is_true()


func test_adjacent_pairs_at_span_1_are_not_strained() -> void:
	for start_index in range(ElementWheel.ORDER.size()):
		var first: StringName = ElementWheel.ORDER[start_index]
		var second: StringName = ElementWheel.ORDER[(start_index + 1) % ElementWheel.ORDER.size()]
		var result: CompositionResult = CompositionResolver.resolve([first, second], &"phrase")
		assert_int(result.distance_steps).is_equal(1)
		assert_int(result.kind).override_failure_message(
			"Adjacent pair %s|%s must not be strained" % [first, second]
		).is_equal(CompositionResult.Kind.CHORD)
		assert_str(String(result.imposition_strength)).is_equal("full")
		assert_int(result.var_cost).is_equal(0)


# ─── (c) Clash on overspan: span > 2 is self-Discord, never a fizzle ────────
#
# A three-element composition whose outer span exceeds the two-step cap is a
# CLASH: rejected, self-inflicted Discord, and crucially NOT fizzle_requested —
# the caster does not get the gamble, they get the backlash. Opposed pairs
# (distance 5) are rejected as OPPOSED before any span maths runs. Both paths
# are table-driven off the wheel.


func test_three_element_compositions_with_span_over_two_clash() -> void:
	var wheel_size: int = ElementWheel.ORDER.size()
	var clash_cases: Array[Array] = []
	for first_index in range(wheel_size):
		for second_index in range(first_index + 1, wheel_size):
			for third_index in range(second_index + 1, wheel_size):
				var elements: Array[StringName] = [
					ElementWheel.ORDER[first_index],
					ElementWheel.ORDER[second_index],
					ElementWheel.ORDER[third_index],
				]
				if ElementWheel.contains_opposed_pair(elements):
					continue
				if ElementWheel.span(elements) > 2:
					clash_cases.append(elements)
	# Sanity: the table must actually exercise the rule.
	assert_bool(clash_cases.size() > 0).is_true()
	for elements: Array[StringName] in clash_cases:
		var result: CompositionResult = CompositionResolver.resolve(elements, &"song")
		assert_int(result.kind).override_failure_message(
			"Span-%d composition %s should CLASH" % [ElementWheel.span(elements), elements]
		).is_equal(CompositionResult.Kind.CLASH)
		assert_bool(result.is_clash()).is_true()
		assert_bool(result.self_inflicted_discord).is_true()
		assert_bool(result.rejected).is_true()
		assert_str(String(result.failure_id)).is_equal("span_exceeds_two")
		assert_bool(result.fizzle_requested).override_failure_message(
			"Clash %s is self-Discord, not a fizzle" % elements
		).is_false()


func test_opposed_pairs_are_rejected_as_opposed_not_strained_or_clashed() -> void:
	# Distance 5 is the far side of the wheel: contains_opposed_pair fires
	# before chord/triad resolution, so an opposed pair is never priced as a
	# span-5 strain and never reaches the clash path.
	for pair: Array in ElementMatrix.clash_pairs():
		var first: StringName = pair[0]
		var second: StringName = pair[1]
		assert_int(ElementWheel.distance(first, second)).is_equal(5)
		var result: CompositionResult = CompositionResolver.resolve([first, second], &"note")
		assert_int(result.kind).override_failure_message(
			"Opposed pair %s|%s" % [first, second]
		).is_equal(CompositionResult.Kind.OPPOSED)
		assert_bool(result.is_opposed()).is_true()
		assert_bool(result.rejected).is_true()
		assert_str(String(result.failure_id)).is_equal("opposed_elements")
		assert_bool(result.fizzle_requested).is_false()
		# An opposed pair inside a three-element composition is also OPPOSED,
		# not a clash — the opposed check precedes the span cap.
		for third: StringName in ElementWheel.ORDER:
			if third == first or third == second:
				continue
			var triple: CompositionResult = CompositionResolver.resolve(
				[first, second, third], &"note"
			)
			assert_int(triple.kind).is_equal(CompositionResult.Kind.OPPOSED)
